#!/bin/sh
set -eu

REPO_OWNER="austinwitherspoon"
REPO_NAME="webcam_to_hdmi"
BIN_NAME="webcam_to_hdmi"
BIN_ASSET="webcam_to_hdmi-aarch64-unknown-linux-gnu"
BIN_URL="https://github.com/${REPO_OWNER}/${REPO_NAME}/releases/latest/download/${BIN_ASSET}"

INSTALL_PATH="/usr/local/bin/${BIN_NAME}"
SERVICE_PATH="/etc/systemd/system/webcam_to_hdmi.service"
ENV_FILE="/etc/default/webcam_to_hdmi"
TMP_BIN="/tmp/${BIN_NAME}"

# Known-good defaults from austin@canada.lan (RPi 5).
DEFAULT_USB1_CAM_DEV="/dev/v4l/by-path/platform-xhci-hcd.1-usb-0:1:1.0-video-index0"
DEFAULT_USB2_CAM_DEV="/dev/v4l/by-path/platform-xhci-hcd.0-usb-0:1:1.0-video-index0"
DEFAULT_HDMI1_CONNECTOR_ID="35"
DEFAULT_HDMI2_CONNECTOR_ID="44"

need_cmd() {
  if ! command -v "$1" >/dev/null 2>&1; then
    echo "[setup] missing required command: $1" >&2
    exit 1
  fi
}

if [ "$(id -u)" -ne 0 ]; then
  echo "[setup] please run as root (example: curl -fsSL ... | sudo sh)" >&2
  exit 1
fi

case "$(uname -s)" in
  Linux) ;;
  *)
    echo "[setup] this installer only supports Linux" >&2
    exit 1
    ;;
esac

ARCH="$(uname -m)"
case "$ARCH" in
  aarch64|arm64) ;;
  *)
    echo "[setup] warning: expected arm64/aarch64, found ${ARCH}" >&2
    ;;
esac

need_cmd apt-get
need_cmd curl
need_cmd install
need_cmd systemctl

echo "[setup] installing runtime packages..."
export DEBIAN_FRONTEND=noninteractive
apt-get update
apt-get install -y \
  gstreamer1.0-tools \
  gstreamer1.0-plugins-base \
  gstreamer1.0-plugins-good \
  gstreamer1.0-plugins-bad \
  gstreamer1.0-libav \
  gstreamer1.0-alsa \
  gstreamer1.0-gl \
  gstreamer1.0-x \
  libdrm-tests \
  v4l-utils \
  ca-certificates

echo "[setup] disabling desktop compositor for DRM/KMS usage..."
if systemctl list-unit-files | grep -q '^lightdm\.service'; then
  systemctl disable --now lightdm.service || true
fi
if systemctl list-unit-files | grep -q '^display-manager\.service'; then
  systemctl disable --now display-manager.service || true
fi
systemctl set-default multi-user.target || true
systemctl disable --now webcam_weston.service || true

echo "[setup] downloading ${BIN_NAME} from GitHub Releases..."
curl -fL "$BIN_URL" -o "$TMP_BIN"
install -m 0755 "$TMP_BIN" "$INSTALL_PATH"
rm -f "$TMP_BIN"

cam1="$DEFAULT_USB1_CAM_DEV"
cam2="$DEFAULT_USB2_CAM_DEV"

if [ -d /dev/v4l/by-path ]; then
  detected_cam1="$(find /dev/v4l/by-path -maxdepth 1 -type l -name 'platform-xhci-hcd.1-usb-*-video-index0' | grep -v 'usbv2' | sort | head -n 1 || true)"
  detected_cam2="$(find /dev/v4l/by-path -maxdepth 1 -type l -name 'platform-xhci-hcd.0-usb-*-video-index0' | grep -v 'usbv2' | sort | head -n 1 || true)"

  if [ -n "$detected_cam1" ]; then
    cam1="$detected_cam1"
  fi
  if [ -n "$detected_cam2" ]; then
    cam2="$detected_cam2"
  fi
fi

conn1="$DEFAULT_HDMI1_CONNECTOR_ID"
conn2="$DEFAULT_HDMI2_CONNECTOR_ID"
if command -v modetest >/dev/null 2>&1; then
  modetest_out="$(modetest -M vc4 -c 2>/dev/null || true)"
  c1="$(printf '%s\n' "$modetest_out" | awk '/^[0-9]+/{id=$1} /HDMI-A-1/{print id; exit}')"
  c2="$(printf '%s\n' "$modetest_out" | awk '/^[0-9]+/{id=$1} /HDMI-A-2/{print id; exit}')"
  if [ -n "$c1" ]; then
    conn1="$c1"
  fi
  if [ -n "$c2" ]; then
    conn2="$c2"
  fi
fi

echo "[setup] writing ${ENV_FILE}"
cat > "$ENV_FILE" <<EOF
# Auto-generated by deploy/setup.sh
USB1_CAM_DEV=$cam1
USB2_CAM_DEV=$cam2
HDMI1_CONNECTOR_ID=$conn1
HDMI2_CONNECTOR_ID=$conn2
WIDTH=1920
HEIGHT=1080
FPS=30
POLL_MS=1000
CAMERA_RETRY_MS=5000
DRM_CARD_DEV=/dev/dri/card1
EOF
chmod 0644 "$ENV_FILE"

echo "[setup] installing systemd unit"
cat > "$SERVICE_PATH" <<'EOF'
[Unit]
Description=Dual webcam to HDMI mapper
After=network-online.target
Wants=network-online.target

[Service]
Type=simple
EnvironmentFile=-/etc/default/webcam_to_hdmi
ExecStart=/usr/local/bin/webcam_to_hdmi
Restart=always
RestartSec=2
User=root
Group=root

[Install]
WantedBy=multi-user.target
EOF
chmod 0644 "$SERVICE_PATH"

echo "[setup] validating key gstreamer plugins"
gst-inspect-1.0 kmssink >/dev/null
gst-inspect-1.0 v4l2src >/dev/null
gst-inspect-1.0 jpegdec >/dev/null

echo "[setup] enabling and starting webcam_to_hdmi.service"
systemctl daemon-reload
systemctl enable webcam_to_hdmi.service
systemctl restart webcam_to_hdmi.service

echo "[setup] install complete"
echo "[setup] service status:"
systemctl --no-pager --full status webcam_to_hdmi.service || true