#!/usr/bin/env bash
set -euo pipefail

ENV_FILE="/etc/default/webcam_to_hdmi"

echo "[setup] Installing runtime packages..."
export DEBIAN_FRONTEND=noninteractive
apt-get update
apt-get install -y \
  gstreamer1.0-tools \
  gstreamer1.0-plugins-base \
  gstreamer1.0-plugins-good \
  gstreamer1.0-plugins-bad \
  gstreamer1.0-libav \
  gstreamer1.0-alsa \
  gstreamer1.0-gl \
  gstreamer1.0-x \
  libdrm-tests \
  v4l-utils

echo "[setup] Disabling desktop compositor to free DRM/KMS for webcam_to_hdmi..."
if systemctl list-unit-files | grep -q '^lightdm\.service'; then
  systemctl disable --now lightdm.service || true
fi
if systemctl list-unit-files | grep -q '^display-manager\.service'; then
  systemctl disable --now display-manager.service || true
fi
systemctl set-default multi-user.target || true

# Pick the first two USB camera by-path nodes that carry index0 streams.
cam1=""
cam2=""
if [ -d /dev/v4l/by-path ]; then
  # Prefer stable root-port mappings on Pi 5: xhci-hcd.1 and xhci-hcd.0.
  cam1="$(find /dev/v4l/by-path -maxdepth 1 -type l -name 'platform-xhci-hcd.1-usb-*-video-index0' | grep -v 'usbv2' | sort | head -n 1 || true)"
  cam2="$(find /dev/v4l/by-path -maxdepth 1 -type l -name 'platform-xhci-hcd.0-usb-*-video-index0' | grep -v 'usbv2' | sort | head -n 1 || true)"

  mapfile -t candidates < <(find /dev/v4l/by-path -maxdepth 1 -type l -name '*usb*video-index0' | sort)
  if [ "${#candidates[@]}" -eq 0 ]; then
    mapfile -t candidates < <(find /dev/v4l/by-path -maxdepth 1 -type l -name '*video-index0' | grep -Ev '(codec|pisp_be)' | sort)
  fi

  declare -A seen_targets
  cams=()
  for path in "${candidates[@]}"; do
    target="$(readlink -f "$path" || true)"
    if [ -z "$target" ]; then
      continue
    fi
    if [ -n "${seen_targets[$target]:-}" ]; then
      continue
    fi
    seen_targets[$target]=1
    cams+=("$path")
  done

  if [ "${#cams[@]}" -eq 0 ]; then
    mapfile -t cams < <(find /dev/v4l/by-path -maxdepth 1 -type l -name '*video-index0' | grep -Ev '(codec|pisp_be)' | sort)
  fi

  if [ -z "$cam1" ] && [ "${#cams[@]}" -ge 1 ]; then
    cam1="${cams[0]}"
  fi
  if [ -z "$cam2" ]; then
    for path in "${cams[@]}"; do
      if [ "$path" != "$cam1" ]; then
        cam2="$path"
        break
      fi
    done
  fi
fi

if [ -z "$cam1" ]; then
  cam1="/dev/v4l/by-path/platform-xhci-hcd.1-usb-0:1:1.0-video-index0"
fi
if [ -z "$cam2" ]; then
  cam2="/dev/v4l/by-path/platform-xhci-hcd.0-usb-0:1:1.0-video-index0"
fi

# Detect connector IDs for HDMI-A-1 and HDMI-A-2 when modetest is available.
conn1="32"
conn2="41"
if command -v modetest >/dev/null 2>&1; then
  modetest_out="$(modetest -M vc4 -c 2>/dev/null || true)"
  c1="$(printf '%s\n' "$modetest_out" | awk '/^[0-9]+/{id=$1} /HDMI-A-1/{print id; exit}')"
  c2="$(printf '%s\n' "$modetest_out" | awk '/^[0-9]+/{id=$1} /HDMI-A-2/{print id; exit}')"
  if [ -n "$c1" ]; then
    conn1="$c1"
  fi
  if [ -n "$c2" ]; then
    conn2="$c2"
  fi
fi

echo "[setup] Writing $ENV_FILE"
cat > "$ENV_FILE" <<EOF
# Auto-generated by deploy/setup_pi.sh
USB1_CAM_DEV=$cam1
USB2_CAM_DEV=$cam2
HDMI1_CONNECTOR_ID=$conn1
HDMI2_CONNECTOR_ID=$conn2
WIDTH=1920
HEIGHT=1080
FPS=30
POLL_MS=1000
CAMERA_RETRY_MS=5000
DRM_CARD_DEV=/dev/dri/card1
EOF

chmod 0644 "$ENV_FILE"

echo "[setup] Environment configured:"
cat "$ENV_FILE"

echo "[setup] Verifying key plugins"
gst-inspect-1.0 waylandsink >/dev/null
gst-inspect-1.0 v4l2src >/dev/null
gst-inspect-1.0 jpegdec >/dev/null

echo "[setup] Raspberry Pi setup complete."
